 ---
title: "sa_drugmarket_datascape"
format: html
editor: visual
---

Welcome to the Drug Market Datascape!
 
## Over of the data

```{r}
# Drug Market Tables
# Tables

# Load packages
pacman::p_load(
  ggplot2 ,    # plotting and graphing results
  rlang,      # read in excel files
  forcats,    # read in excel files
  broom,      # tidy code
  readxl,     # read in excel files
  pacman,     # loading and reading in packages
  rio,        # importing data
  here,       # relative file pathways
  janitor,    # data cleaning and tables
  lubridate,  # working with dates
  matchmaker, # dictionary-based cleaning
  epikit,     # age_categories() function
  tidyverse,  # data management and visualization
  gtsummary,  # logistic regression and plotting results
  gt,         # for gtsummary
  flextable,  # table creation and manipulating
  finalfit,   # logistic regression and plotting results
  jtools,
  corrplot,
  codebookr,
  codebook,
  sjlabelled,
  likert,
  kableExtra,
  haven,
  tableone, 
  summarytools
)

# load data
#
load(
  here::here("data_processed", "drug_market_working.rda"))

load(
  here::here("data_processed", "drug_market_factors.rda"))

# Create a theme for figures, tables and all processed text

apa_theme <- function (ft)  {
  ft %>%
    flextable::font(fontname = "Times New Roman", part = "all") %>%
    flextable::fontsize(size = 10, part = "all") %>%
    flextable::align(align = "left", part = "all") %>%
    flextable::align(align = "left", part = "header") %>%
    #flextable::rotate(rotation = "lrtb", align = "top", part = "body") %>%
    flextable::border_remove() %>%
    flextable::hline_top(border = officer::fp_border(width = 1.5), part = "all") %>%
    flextable::hline_bottom(border = officer::fp_border(width = 1.5), part = "all") %>%
    flextable::hline_bottom(border = officer::fp_border(width = 1.5), part = "header") %>%
    flextable::hline_bottom(border = officer::fp_border(width = 1.5), part = "footer") %>%
    flextable::hline_bottom(border = officer::fp_border(width = 2), part = "all") %>%
    flextable::autofit()
}

# Set the theme to compact [reduce spacing around text and numbers]

## Set the theme as a compact [spacing]
set_gtsummary_theme(theme_gtsummary_compact())

```

```{r}
sa_drugmarket <- drug_market %>%
  dplyr::select(city.factor:link.yn)

ff_glimpse(sa_drugmarket)

```

Summary of the data

```{r drug-market, results="asis", warning=FALSE}

print(dfSummary(sa_drugmarket, 
                varnumbers   = FALSE,
                valid.col    = FALSE,
                graph.magnif = 0.76), 
      max.tbl.height = 300,
      method = "render")
```

### Characteristics of People Who Supply Drugs 

### Sell to Sellers

### Sell to Consumers

### Seller Stock and Sales During COVID-19

## DISCUSSION
